engines:
  tailor:
    enabled: true
    exclude_paths:
    - Playgrounds/
    - readme.playground/
    checks:
      trailing-whitespace:
        enabled: false
        
ratings:
  paths:
  - "**.swift"

except:
  - trailing-whitespace
