language: objective-c
osx_image: xcode7.3
xcode_project: Medea.xcodeproj

addons:
  code_climate:
    repo_token: d74f9806f3845685ee2154bdf097f5caed7651361ea318e79b07a7427dd87a73

matrix:
  include:
  - script: xcodebuild -workspace Medea.xcworkspace -scheme Medea_OSX -destination "platform=OS X" clean build test | xcpretty
    env: Type=OSX
  - script: xcodebuild -workspace Medea.xcworkspace -scheme Medea_iOS -destination "platform=iOS Simulator,name=iPad Pro" clean build test
    env: Type=iOS
  - script: xcodebuild -workspace Medea.xcworkspace -scheme Medea_tvOS -destination "platform=tvOS Simulator,name=Apple TV 1080p" clean build test
    env: Type=tvOS
