language: objective-c
osx_image: xcode7.3
xcode_project: Medea.xcodeproj

addons:
    code_climate:
        repo_token: d74f9806f3845685ee2154bdf097f5caed7651361ea318e79b07a7427dd87a73

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
  
script:
   - xcodebuild -project Medea.xcodeproj -scheme Medea_OSX CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test
   - xcodebuild -project Medea.xcodeproj -scheme Medea_iOS -destination "platform=iOS Simulator,name=iPad Pro" test
   - xcodebuild -project Medea.xcodeproj -scheme Medea_tvOS -destination "platform=tvOS Simulator,name=Apple TV 1080p" test
